# Generated by Django 4.2.2 on 2023-08-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingTable',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='Menu',
        ),
    ]
